### ISSUE TITLE
Error opening MBA SuperDrive "/dev/sr0"

### ISSUE THREAD

**Issue by shurikenZ22** [onmomo/superdrive-enabler#4]
Trying to compile this in Linux Mint 20.1, I get this issue:

```
gcc -o superdriveEnabler superdriveEnabler.c
superdriveEnabler.c: In function ‘superdriveEnabler’:
superdriveEnabler.c:37:9: warning: implicit declaration of function ‘close’; did you mean ‘pclose’? [-Wimplicit-function-declaration]
   37 |         close(fd);
      |         ^~~~~
      |         pclose
```

I tried executing it anyway and it resulted in this:

```
/superdriveEnabler /dev/sr0
Error opening MBA SuperDrive "/dev/sr0".
```

My SuperDrive has a disc inserted, but doesn't activate with this.

Edit: Seems it does work however you must execute it right away after connecting the SuperDrive to the computer.
Edit2: It seems the change is not permanent. Once you unplug it, superdrive-enabler needs to be executed again next time you want to use the SuperDrive

**Comment by DolleDries** [comment]
Can't get it working on Ubuntu 20.04. When I insert a disc it spins but doesnot shown anything. On the macbook (2009) it came from the drive works perfectly... Just on that macbook though. Could i be that the drive is too old???
